org.gradle.jvmargs=-Xmx1024m -XX:+UseSerialGC -Dfile.encoding=UTF-8
org.gradle.workers.max=1
org.gradle.parallel=false
org.gradle.vfs.watch=false
android.builder.sdk.download=false
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
android.enableCxx=false
android.lintOptions.checkReleaseBuilds=false
android.lintOptions.abortOnError=false
systemProp.gradle.user.home=D:/gradle_cache


