module.exports = {
  ROLES: {
    CUSTOMER: 'CUSTOMER',
    DRIVER: 'DRIVER',
    ADMIN: 'ADMIN',
    OPERATIONS: 'OPERATIONS',
    CALL_CENTER: 'CALL_CENTER'
  },
  
  BOOKING_STATUS: {
    SEARCHING_DRIVER: 'SEARCHING_DRIVER',
    DRIVER_REQUESTED: 'DRIVER_REQUESTED',
    DRIVER_ACCEPTED: 'DRIVER_ACCEPTED',
    DRIVER_ASSIGNED: 'DRIVER_ASSIGNED',
    PAYMENT_PENDING: 'PAYMENT_PENDING',
    CONFIRMED: 'CONFIRMED',
    RIDE_STARTED: 'RIDE_STARTED',
    RIDE_COMPLETED: 'RIDE_COMPLETED',
    PAYMENT_COMPLETED: 'PAYMENT_COMPLETED',
    REVIEW_PENDING: 'REVIEW_PENDING',
    CANCELLED: 'CANCELLED',
    REFUNDED: 'REFUNDED'
  },

  BOOKING_TYPE: {
    BOOK_NOW: 'BOOK_NOW',
    BOOK_LATER: 'BOOK_LATER'
  },

  TRIP_TYPES: {
    FULL_TRIP: 'FULL_TRIP',
    HALF_TRIP: 'HALF_TRIP',
    CROSS_GHAT: 'CROSS_GHAT',
    EVENT: 'EVENT'
  },

  BOAT_CATEGORIES: {
    MOTOR_BOAT: 'MOTOR_BOAT',
    MANUAL_ROW_BOAT: 'MANUAL_ROW_BOAT',
    LUXURY_BAJRA: 'LUXURY_BAJRA',
    SPEED_BOAT: 'SPEED_BOAT',
    EV_BOAT: 'EV_BOAT'
  },

  PAYMENT_MODES: {
    PAY_AFTER_RIDE: 'PAY_AFTER_RIDE',
    ONLINE_PREPAID: 'ONLINE_PREPAID'
  },

  PAYMENT_STATUS: {
    PENDING: 'PENDING',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED',
    REFUNDED: 'REFUNDED',
    CASH_COLLECTED: 'CASH_COLLECTED'
  },

  CANCELLATION_REFUND_SLABS: {
    BEFORE_12_HOURS: 0.80, // 80% refund
    BEFORE_6_HOURS: 0.70,  // 70% refund
    BEFORE_3_HOURS: 0.50,  // 50% refund
    LESS_THAN_3_HOURS: 0.0 // 0% refund
  }
};
